### PR TITLE
MPIB slides

### PR DESCRIPTION
**Pull request by adswa**
Hey @lnnrtwttkhn, FYI: I have started creating slides (no hands-on things, just general explanations of concepts and logistics). Did it here as I had all my figures in here already, but we can migrate this to our own repo.

### CODE REVIEW

**Comment by adswa** [comment]
Cloning and getting the data worked! :) 
will add the slides with screenshots on how to do this tomorrow :)

**Comment by lnnrtwttkhn** [comment]
Fantastic! Thank you!

**Comment by adswa** [comment]
Shall we see whether we can document me pushing something back, too?

**Comment by lnnrtwttkhn** [comment]
Looks good!

> Shall we see whether we can document me pushing something back, too?

Yes, good idea! Then we can really present the full circle of the collaborative process!

**Comment by adswa** [comment]
I can't collaborate on your GitLab instance (I'm not a member, can't create a fork an PR). Re-do on GitHub?

**Comment by lnnrtwttkhn** [comment]
> I can't collaborate on your GitLab instance (I'm not a member, can't create a fork an PR). Re-do on GitHub?

I just invited you with "Developer" access to the repo. I would like to try on the MPIB's GitLab instance since this might be the platform that many people (will) likely use (if they don't have a GitHub account).

Could you try again and let me know if it works? Thanks!

**Comment by adswa** [comment]
>  I would like to try on the MPIB's GitLab instance since this might be the platform that many people (will) likely use (if they don't have a GitHub account).

Agreed! 

But: I can't sign in or sign up, whoever runs your GitLab instance would need to create an account for me first. :/

**Comment by lnnrtwttkhn** [comment]
Uff, that's annoying! I'll ask and let you know ASAP!

**Comment by adswa** [comment]
Good luck. I somewhat doubt that they would let an outside join, though. We could pretend I have access, and document the necessary steps (screenshots of forking, adding the remote, pushing a change, merging it), or you could ask a colleague who is signed up on the MPIB's GitLab?

**Comment by lnnrtwttkhn** [comment]
You should have access now. Can you try?

**Comment by adswa** [comment]
Ha, cool! thanks :)

**Comment by lnnrtwttkhn** [comment]
Hey Adina, did you yet commit the files for the collaborative workflow (e.g., `../pics/gitlabmerge1.png` etc.)?

I could not find them in the repo! Happy to add them myself.

**Comment by adswa** [comment]
Thx for reminding me - should have pushed everything right now.

**Comment by adswa** [comment]
oh my god we can merge

**Comment by lnnrtwttkhn** [comment]
u sure? 😱

**Comment by adswa** [comment]
:heart_eyes:

**Comment by adswa** [comment]
do it!

**Pull request merged**
